### ISSUE TITLE
Isn't working for me. What am I missing?

### ISSUE THREAD

**Issue by wcarson** [davelosert/semantic-release-github-actions-tags#4]
I think I have this plugin configured correctly per the documentation, but the plugin doesn't seem to get loaded. Below is my releaserc.yml and semantic-release output:

**releaserrc.yml**
```yaml
---
githubUrl: https://our-github-enterprise
githubApiPathPrefix: '/api/v3'
branches:
  - main
tagFormat: v${version}
plugins:
  - '@semantic-release/commit-analyzer'
  - '@google/semantic-release-replace-plugin'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/git'
  - '@semantic-release/github'
  - 'semantic-release-github-actions-tags' # <-- included plugin
verifyConditions:
  - '@semantic-release/git'
  - '@semantic-release/github'
analyzeCommits:
  - path: '@semantic-release/commit-analyzer'
    releaseRules:
      - type: fix
        release: patch
      - (removed for brevity)
generateNotes:
  - path: '@semantic-release/release-notes-generator'
    writerOpts:
      groupBy: type
      commitGroupsSort:
        - feat
        - fix
        - refactor
        - docs
      commitsSort: header
    types:
      - type: feat
        section: Features
      - (removed for brevity)
    presetConfig: true
prepare:
  - path: '@google/semantic-release-replace-plugin'
    replacements:
      - files: ['package.json']
        from: '"version": ".*"'
        to: '"version": "${nextRelease.version}"'
  - path: '@semantic-release/changelog'
    changelogFile: './CHANGELOG.md'
  - path: '@semantic-release/git'
    message: 'chore: v${nextRelease.version} release'
    assets:
      - package.json
      - dist
      - CHANGELOG.md
publish:
  - path: '@semantic-release/github'
success:
  - '@semantic-release/github'
fail:
  - '@semantic-release/github'
 ```

**semantic-release run**
![image](https://user-images.githubusercontent.com/963939/219781808-3d1fb057-be51-41f2-8b0f-ff1da7a2112f.png)
